#
# TotalFreedomMod Configuration
#

# Generic server information
server:
  # You should change this to your server's name
  name: TotalFreedom

  # The address your server is located at. Please do not include the port.
  address: play.totalfreedom.me

  # Shown at the server list - Please note that support for %mcversion% has been withdrawn
  motd: TotalFreedom &8- The Original All-Op Server!

  # Every word in the MOTD will be a different color unless prefixed by a color code
  colorful_motd: true

  # MOTD Modification
  motds:
    ban: '&cYou are banned.'
    staffmode: '&cServer is closed.'
    lockdown: '&cServer is in lock-down.'
    whitelist: '&cWhitelist enabled.'
    full: '&cServer is full.'

  # Shown on join as a title
  login_title:
    title: '&7Welcome to &6TotalFreedom&7!'
    subtitle: '&eThe Original All-Op Server!'

  # All players who show up as owner
  owners:
    - Demonic_Mario

  # All players who show up as executive
  executives: []

  # All players who show up as assistant executive
  assistant_executives: []

  # All those who can manage the master builder list
  master_builder_management: []

  # URL players should appeal for bans at
  ban_url: ''

  # URL players should appeal for permanent bans at
  indefban_url: ''

  # What to display at the top of the tab list
  tablist_header: ''

  # What to display at the bottom of the tab list
  tablist_footer: ''

# Discord
discord:
  # If you do not have a token, make a bot account and get one at https://discordapp.com/developers/applications/me
  token: ''
  # The official discord server's ID for this server
  server_id: ''
  # Channel to send /report messages to
  report_channel_id: ''
  # Channel for discord to minecraft and vice-versa
  chat_channel_id: ''
  # Do you want roles to sync with the server?
  role_sync: false
  # Master Builder role ID
  master_builder_role_id: ''
  # Trial Mod role ID
  trial_mod_role_id: ''
  # Mod role ID
  mod_role_id: ''
  # Admin role ID
  admin_role_id: ''
  # Developer role ID
  developer_role_id: ''
  # Assistant Executive Admin role ID
  assistant_executive_role_id: ''
  # Executive Admin role ID
  executive_role_id: ''
  # Owner role ID
  server_owner_role_id: ''

# Reddit
reddit:
  # Name of your subreddit (the r/NAME, excluding r/)
  subreddit_name: 'TotalFreedom'
  # Username of the bot account
  username: ''
  # Bot account password
  password: ''
  # Developer app id (Make one at https://www.reddit.com/prefs/apps (make sure the type is script))
  client_id: ''
  # Developer app secret
  client_secret: ''
  # Donator flair ID
  donator_flair_id: ''
  # Master Builder flair ID
  master_builder_flair_id: ''
  # Trial Mod flair ID
  trial_mod_flair_id: ''
  # Mod flair ID
  mod_flair_id: ''
  # Admin flair ID
  admin_flair_id: ''
  # Developer flair ID
  developer_flair_id: ''
  # Assistant Executive Admin flair ID
  assistant_executive_flair_id: ''
  # Executive Admin flair ID
  executive_flair_id: ''
  # Owner flair ID
  server_owner_flair_id: ''

# AMP
amp:
  # URL - do not leave a trailing forward slash
  url: ''
  # Username
  username: ''
  # Password
  password: ''
  
# The shop
shop:
  # Enable the shop
  enabled: true

  # Shop title
  title: '&e&lTotalFreedom Shop'
  
  # Shop prefix
  prefix: '&8[&eTF Shop&8]'

  # How many coins to voters get per vote?
  coins_per_vote: 20

  # Chat reactions
  reactions:

    # Enable chat reactions?
    enabled: true

    # How much time (in seconds) before a new reaction prompt is made
    interval: 300

    # How much time do players have to react
    time: 30

    # How many coins do winners get?
    coins_per_win: 5

    # How long is the random string (in characters)?
    string_length: 10

  # Item prices
  prices:
    grappling_hook: 100
    lightning_rod: 1000
    fire_ball: 500
    rideable_pearl: 700
    stacking_potato: 300
    clown_fish: 1500

# Staff list
stafflist:

  # The amount of hours after which staff may be removed from the admin list
  clean_threshold_hours: 167

  # Give the default CONSOLE admin privileges.
  # Handy in development environments.
  console_is_admin: true
  
# CoreProtect
coreprotect:
  enabled: false
  host: 'localhost'
  port: '3306'
  username: ''
  password: ''
  database: 'coreprotect'

# ForceIP configuration
forceip:
  enabled: false

  # The port players should use to connect to your server; only applies to forceip
  port: 25565

  # The kick message sent to players when logging in with the wrong hostname
  kickmsg: You have been kicked from the server - Please connect using %address%

# TotalFreedom Social Media Links, casing will be preserved
social_links:
  Forum: 'https://forum.totalfreedom.me'
  Website: 'https://totalfreedom.me/'
  Discord: 'https://discordapp.com/invite/XXjmAmV/'

donation:
  proboards_url: ''
  donator_group_id: ''
  session_id: ''
  csrf_token: ''

# Blocking certain events
allow:
  fire_place: false
  fire_spread: false
  fluid_spread: false
  lava_place: false
  lava_damage: false
  water_place: false
  tnt_minecarts: false
  explosions: false
  redstone: true
  fireworks: false
  frostwalker: false
  unsafe_enchantments: true
  bells: true
  armorstands: true
  minecarts: false
  clearonjoin: false
  structureblocks: false
  jigsaws: false
  grindstones: false
  jukeboxes: false
  spawners: false
  beehives: false
  respawnanchors: false
  auto_tp: false
  auto_clear: false

# Blocked commands:
#
# How blocked commands work:
# All sections described below are delimited by colon characters.
# Make sure that you block a command by its main command name, not an alias
# as all aliases are blocked by default. Commands are case-insensitive.
#
# * The first section is a letter which indicates which rank may use this command
#   Valid ranks:
#   n - Nobody (Completely disabled)
#   c - Trial Mods (Console)
#   m - Admins (Console)
#   s - Staff (Any in-game admin)
#   o - Ops (Non-Ops won't be able to use it)
#
# * The second section is a letter which indicates what to do when a player executes that command.
#   Valid actions:
#   b - Block the command
#   a - Block the command and auto-eject that player (for ops and below)
#   u - Block the command and Return an "Unknown command" message (Used to hide commands)
#
# * The third section is the command to be blocked, prefixed with a slash
#
# * The fourth section is the message to send to the player when executing that command.
#   This should be ommited if unwanted. ChatColors are supported with the &-key. By default
#   -the starting ChatColor is set to gray. You can use the default 'That command is blocked.' message
#   by using a single underscore.
#
# Examples:
#   - 'n:b:/mail sendall:&4You can't send mails to everyone!'
#   - 's:a:/stop'
#   - 'n:b:/ban:_'
#
blocked_commands:
  # Disabled commands
  - 'n:b:/time:Server-side time changing is disabled. Please use /ptime to set your own personal time.'
  - 'n:b:/gamemode:Use /creative and /survival to set your gamemode.'
  - 'n:b:/pardon:_'
  - 'n:b:/ban-ip:_'
  - 'n:b:/pardon-ip:_'
  - 'n:b:/toggledownfall:_'
  - 'n:b:/enderchest:_'
  - 'n:b:/spreadplayers:_'
  - 'n:b:/execute:_'
  - 'n:b:/blockdata:_'
  - 'n:b:/clearhistory:_'
  - 'n:b:/save-on:_'
  - 'n:b:/save-off:_'
  - 'n:b:/playsound:_'
  - 'n:b:/skinrestorer:_'
  - 'n:b:/packet:_'
  - 'n:b:/thaw:_'
  - 'n:b:/setjail:_'
  - 'n:b:/function:_'
  - 'n:b:/data:_'
  - 'n:b:/datapack:_'
  - 'n:b:/bossbar:_'
  - 'n:b://forceload:_'

  # Staff commands
  - 's:b:/save-all:_'
  - 's:b:/kick:_'
  - 's:b:/socialspy:_'
  - 's:b:/replaceitem:_'
  - 's:b:/kill:_'
  - 's:b://generate:_'
  - 's:b://:_'
  - 's:b:/superpickaxe:_'
  - 's:b:/brush:_'
  - 's:b:/size:_'
  - 's:b://mask:_'
  - 's:b:/mat:_'
  - 's:b://butcher:_'
  - 's:b:/scoreboard:_'
  - 's:b:/setspawn:_'
  - 's:b://snow:_'
  - 's:b:/tellraw:_'
  - 's:b:/forestgen:_'
  - 's:b:/setidletimeout:_'
  - 's:b:/mail sendall:_'
  - 's:b:/eco reset:_'
  - 's:b:/mask:_'
  - 's:b:/gmask:_'
  - 's:b:/lrbuild:_'
  - 's:b:/defaultgamemode:_'
  - 's:b:/reload:_'
  - 's:b:/title:_'
  - 's:b:/worldborder:_'
  - 's:b:/weather:_'
  - 's:b:/tpall:_'
  - 's:b:/setblock:_'
  - 's:b:/green:_'
  - 's:b:/gamerule:_'
  - 's:b:/togglejail:_'
  - 's:b:/fill:_'
  - 's:b:/flood:_'
  - 's:b:/team:_'
  - 's:b:/loot:_'
  - 's:b:/schedule:_'

# Automatically wipe dropped objects
auto_wipe: true

# Nuking prevention
nukemonitor:
  enabled: true
  count_break: 100
  count_place: 40
  range: 10.0

freecam_trigger_count: 10
explosive_radius: 4.0

# Show all attempted commands in the log, will result in duplicate log messages
preprocess_log: true

# Disable certain events
disable:
  night: true
  weather: true


# Enable misc. features
landmines_enabled: false
mp44_enabled: false
tossmob_enabled: false
4chan_enabled: false

# Moblimiter
moblimiter:
  enabled: true
  max: 50
  disable:
    dragon: true
    ghast: true
    slime: true
    giant: true

# Flatlands
flatlands:
  generate: true

  # Flatlands generation parameters - Uses CleanroomGenerator syntax - http://dev.bukkit.org/server-mods/cleanroomgenerator/
  generate_params: 16,stone,32,dirt,1,grass_block

# Admin-Only Mode
staff_only_mode: false

# Toggle Chat
toggle_chat: true

# Host Sender Names - Names that indicate automated services or host-based consoles you want to block from using some commands.
# Make sure these are all lower-case.
host_sender_names:
  - rcon
  - console

# Announcer
announcer:
  enabled: true

  # Interval between announcements, in seconds.
  interval: 600

  # Prefix for all announcements
  prefix: '&5[&eTotalFreedom&5] &b'

  announcements:
  - 'Be sure to visit our forums at &6https://forum.totalfreedom.me/'
  - 'If you are not OP, be sure to ask!'
  - 'Somebody breaking the rules? Report it! /report <user> <reason>'
  - 'Griefing is not allowed!'
  - 'Hacked clients are allowed!'
  - 'Interested in becoming admin? Type "/ai" for more information!'
  - 'You may view all online administrators via "/list -a"'
  - 'Save your buildings via WorldEdit! http://totalfreedom.me for more information!'
  - 'You may contact TotalFreedom support on Twitter! https://tiny.re/tfsupport'
  - 'You may download TotalFreedomMod here: https://tiny.re/tfm+'
  - 'scripthead is the owner of TotalFreedom.'
  - 'markbyron is the founder of TotalFreedom.'
  - 'Server lagging? Check the lag via "/tps"'
  - 'You are allowed to record and stream videos on TotalFreedom.'
  - 'Player vs player while in creative or god mode is forbidden!'
  - 'Spawn killing is forbidden!'
  - 'Invisible potions are allowed!'
  - 'Serial griefing and trolling will result in an indefinite ban!'
  - 'Racism, nazism, and sexism are strictly forbidden!'
  - 'Join our Discord server! Link: https://discordapp.com/invite/XXjmAmV/'

# What to display in the staffinfo command.
staffinfo:
  - '&bHow to apply for staff on the TotalFreedom Server:'
  - ' &6- Do not ask for staff in game'
  - ' &2- Be helpful within the server'
  - ' &6- Report those breaking the rules'
  - ' &2- And apply on our forums at the link:'
  - '    &9https://forum.totalfreedom.me/'
  
# What to display in the vote command.
votinginfo:
  - '&bVoting Links:'
  - ' &6- https://minecraft-mp.com/server/228386/vote/'
  - ' &2- https://minecraft-server-list.com/server/443272/vote/'
  - ' &6- https://topg.org/Minecraft/in-518809'

# What to display in the Master Builder info command.
masterbuilderinfo:
  - '&bHow to apply for Master Builder on the TotalFreedom Server:'
  - ' &6- Do not ask for Master Builder in game'
  - ' &2- Screenshot some of your previous builds (be ready to prove that the builds are yours)'
  - ' &6- Copy the template and create a thread on our forums'
  - ' &2- Template:'
  - '    &9bit.ly/TFMasterBuilderTemplate'

# Famous players - cannot be banned by username
famous_players:
  - honeydew
  - xephos
  - captainsparklez
  - truemu
  - kiershar
  - fvdisco
  - sethbling
  - notch
  - jeb_
  - gamechap
  - bertiechap
  - vechs
  - antvenom
  - chimneyswift
  - deadmau5
  - etho
  - ethoslab
  - skydoesminecraft
  - skythekidrs
  - tobyturner
  - xxslyfoxhoundxx
  - paulsoaresjr
  - sips_
  - deadlox
  - xxslyxx
  - jeromeasf
  - dinnerbone
  - grumm
  - grum
  - evilseph
  - cavemanfilms
  - herobrine
  - whiteboy7thst
  - stampylonghead
  - stampylongnose
  - dantdm
  - gizzy14gazza
  - furiousdestroyer

# Pet Protect - Prevent tamed pets from being killed.
petprotect:
  enabled: true

# Logviewer
logs:
  url: ''
  secret: ''

# Mojang service checker
service_checker_url: http://status.mojang.com/check

# HTTPD server
httpd:
  enabled: true
  host: play.totalfreedom.me
  port: 28966
  public_folder: ./public_html

# Inactivity Auto-Kick (Requires Essentials)
autokick:
  enabled: true

  # Percentage of server player capacity used at which players will be automatically kicked for being inactive. Range: 0.0 - 1.0
  threshold: 0.9

  # Time, in seconds, after which a player should be kicked when inactive
  time: 120
  
# Blocked Chat Codes - Use &code,&code2,&code3 (No spaces)
blocked_chatcodes: '&0,&k,&m,&n'

# Enables certain things like debug logs and console bypasses
developer_mode: false